### PR TITLE
Technical 2-level residual-bootstrap noise to fix invalid matrix issues

### PR DESCRIPTION
**Pull request by IlmariTamminen**
At times, the residual-bootstrap replicates can fail and give errors such as:

```
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 't': Lapack routine dgesv: system is exactly singular: U[1,1] = 0
In addition: Warning message:
In chol.default(S, pivot = TRUE) :
  the matrix is either rank-deficient
```

This can be common with small number of clusters causing invalid matrix calculations. To solve the issue, a feature is proposed in which small, technical 2-level noise can be added to avoid replicating exactly the same numbers many times when the resamples with replacement are taken. This “individualization” resolves the issue while the residual bootstrapping can still produce valid confidence intervals (see below). User defines the ratio (such as `rbootnoise = 0.001`) of how large 2-level noise is added in relation to the 1-level variation (in standard deviations). The default is 0.

Below is an example code to reproduce the error, and how it goes away with rbootnoise = 0.001:

```
library(lme4)
library(lmeresampler)

#Define data
clusters <- 6
clustersize <- 20
measurements <- clusters*clustersize
intercept <- 10
effectsize <- 5
sd1level <- 3
sd2level <- 2

#Create 1-level residuals
set.seed(12345)
testdata <- rnorm(measurements, intercept, sd1level)

#Label controls and tests, 1/2 measurements for both
testdata <- data.frame(dependent = testdata,
                       predictor = c(rep("control", measurements/2), rep("test", measurements/2)),
                       cluster = rep(1:clusters, each=clustersize)
)

#Add fixed effect
testdata[(testdata$predictor == "test"), "dependent"] <- testdata[(testdata$predictor == "test"), "dependent"] + effectsize

#Add random effects
set.seed(12345)
randomeffects <- rnorm(clusters, 0, sd2level)
testdata$dependent <- testdata$dependent + rep(randomeffects, each=clustersize)

boxplot(dependent ~ cluster, testdata)

#Fit model and acquire rboots
model <- lmer(dependent ~ 1 + predictor + (1|cluster), data=testdata, na.action=na.omit)

nrboot <- 2000
set.seed(123) #set.seed(123) does not work when nrboot = 2000 or 5000, and clustersize = 20 or 1000; set.seed(43664765) works. Max seed 2147483647 fails with clustersize = 1000 and nrboot = 10000, not with clustersize = 20.
rboot <- bootstrap(model, .f = fixef, type = "residual", B = nrboot) #Add rbootnoise = 0.001 to fix the issue

#When fails the error is:

#Error in h(simpleError(msg, call)) : 
#  error in evaluating the argument 'x' in selecting a method for function 't': Lapack routine dgesv: system is exactly singular: U[1,1] = 0
#In addition: Warning message:
#  In chol.default(S, pivot = TRUE) :
#  the matrix is either rank-deficient or indefinite
```

Clustered data was simulated 300 times to calculate percentile-CI coverages and the average width with rbootnoise = 0.001. The code below was used, valid results were obtained similar without the noise.

```
library(lme4)
library(lmeresampler)
library(foreach)
library(doParallel)
library(parallel)

#Establish the parallerization of the lmeresampler
ncores <- detectCores()

if(is.na(ncores)) {
  cat("Failed to detect the number of cores, parallerization not used.")
  ncores <- 1
  
} else {
  
  #Preservation of cores for other duties
  if (ncores > 1) {
    if (ncores == 2) {
      ncores <- 1
    } else {
      ncores <- ncores - 2 
    }
    
  }
  cat("The number of detected cores:", detectCores(), "\nCores used for parallerization:", ncores, "\n")
}

cl <- makeCluster(ncores)
registerDoParallel(cl)

nsims <- 300
nrboot <- 1000
i <- 0
coverages <- 0

system.time({
  results <- foreach(i = c(1:nsims), .combine = rbind, .packages = c("blme", "lmeresampler", "boot")) %dopar% {
    
    #Define data
    clusters <- 20
    clustersizes <- abs(round(rnorm(clusters, 20, 5)))
    measurements <- sum(clustersizes)
    intercept <- 0
    effectsize <- 10
    sd1level <- 6
    sd2level <- 3
    
    #Create 1-level residuals
    unevendata <- rnorm(measurements, intercept, sd1level)
    
    #Label controls and tests, 1/2 measurements for both
    ncontrols <- sum(clustersizes[1:(clusters/2)])
    unevendata <- data.frame(dependent = unevendata,
                             predictor = as.factor(c(rep("control", ncontrols), rep("test", measurements-ncontrols))),
                             cluster = as.factor(rep(c(1:clusters), times=clustersizes))
    )
    
    #Add fixed effect
    unevendata[(unevendata$predictor == "test"), "dependent"] <- unevendata[(unevendata$predictor == "test"), "dependent"] + effectsize
    
    #Add random effects
    randomeffects <- rnorm(clusters, 0, sd2level)
    unevendata$dependent <- unevendata$dependent + rep(randomeffects, times=clustersizes)
    
    #Fit model
    model <- lmer(dependent ~ predictor + (1|cluster), data=unevendata, na.action=na.omit)
    
    #Execute residual bootstrapping
    rboot <- bootstrap(model, .f = fixef, type = "residual", B = nrboot, rbootnoise = 0.001)
    
    ci <- confint(rboot, method = "perc", level= 0.95)
    
    return(c(effectsize >= ci[[3]][6] && effectsize <= ci[[4]][6],
             ci[[4]][6] - ci[[3]][6]))
  }
  
})

stopCluster(cl)

coverage <- sum(results[,1])/nsims*100
averagew <- sum(results[,2])/nsims

cat("\nThe 95% coverage was:", coverage, "%\n")
cat("\nThe average CI width was:", averagew, "\n") 

#With rbootnoise = 0.001
# The 95% coverage was: 93.33333 %
#The average CI width was: 5.559433

#With rbootnoise = 0 (i.e. without the technical 2-level noise)
#The 95% coverage was: 92.33333 %
#The average CI width was: 5.706603

```

### CODE REVIEW

**Comment by aloy** [comment]
@IlmariTamminen, This looks good overall. The checks seem to fail on the vignette build now. Could you check whether this was based on your update? I am at a conference now, and might be a bit slow.

**Comment by IlmariTamminen** [comment]
@aloy sure! I removed the commits in RStudio, ran `devtools::check()`, and the vignette errors disappeared. How should we proceed forward, is there something I can do with the vignette issue?

**Comment by IlmariTamminen** [comment]
Okay, I think I solved the vignette issue. See the comments in the commits.

The commit [fd7db66] caused the conflict with the R/bootstrap_nlme.R, but this is trivial. I added a warning in the bootstrap.lme that the technical 2-level noise is currently available only for the LME4 models. I hope the conflict will disappear if the warning is moved further into the resid_bootstrap.lme. But for for some reason I was not able to pass the rbootnoise argument there. Passing the rbootnoise argument for the resid_bootstrap.lme could also resolve warnings about the inconsistency between resid_bootstrap.lme and resid_bootstrap.

**Comment by IlmariTamminen** [comment]
To keep the principle of adding technical 2-level noise uniform, the `rbootnoise` argument now also modifies the 2-level variance in the `vclist`. In addition to the unity of the principle, this feature enables the freedom of the user to run residual bootstrapping even for the data with minimal 2-level variation, when singular fits are encountered in the model fitting. Previously, the residual bootstrapping failed with singular-fit models when the 2-level variance was estimated to be 0. Again, the default is no modification (`rbootnoise = 0`).

Using the multi-predictor example of `vcmodA <- lme4::lmer(mathAge11 ~ mathAge8 + gender + class + (1 | school), data = jsp728)` from the vignette, it was verified that the results of the residual bootstrapping were practically the same with and without `rbootnoise = 0.001`:

```
#The result without rbootnoise:

Bootstrap type: residual 

Number of resamples: 1000 

term   observed   rep.mean         se         bias
1    (Intercept) 14.1577509 14.1314936 0.66815395 -0.026257297
2       mathAge8  0.6388895  0.6402339 0.02502897  0.001344371
3        genderM -0.3571922 -0.3624500 0.33968711 -0.005257732
4 classnonmanual  0.7200815  0.7228748 0.38695334  0.002793348

There were 0 messages, 0 warnings, and 0 errors.


#The result with rbootnoise = 0.001

Bootstrap type: residual 

Number of resamples: 1000 

term   observed   rep.mean         se          bias
1    (Intercept) 14.1577509 14.1514354 0.66165869 -6.315481e-03
2       mathAge8  0.6388895  0.6389309 0.02456213  4.145625e-05
3        genderM -0.3571922 -0.3492369 0.33190467  7.955328e-03
4 classnonmanual  0.7200815  0.7316349 0.38114306  1.155346e-02

There were 0 messages, 0 warnings, and 0 errors.
```

The above-mentioned 300 simulations were run again after adding the new feature, leading to similar valid results as previously:

```
#The 95% coverage was: 93 %
#The average CI width was: 5.688757 
```

**Pull request merged**
